ALTER SESSION SET STATISTICS_LEVEL = ALL;

-- Q1.
SELECT * FROM EMPLOYEES
WHERE EMP_NO LIKE '101%'
OR EMP_NO LIKE '103%';

-- A1.
SELECT * FROM EMPLOYEES
WHERE EMP_NO BETWEEN 10100 AND 10199
OR EMP_NO BETWEEN 10300 AND 10399;

-- Q2.
SELECT NVL(GENDER, 'NON') AS GENDER, COUNT(*)
FROM EMPLOYEES
GROUP BY NVL(GENDER, 'NON');

-- A2.
SELECT /*+INDEX(EMPLOYEES IDX_GENDER)*/ GENDER, COUNT(GENDER)
FROM EMPLOYEES
GROUP BY GENDER;

-- Q3.
SELECT * FROM EMPLOYEES
WHERE GENDER||' '|| LAST_NAME = 'M Radwan';

-- A3.
SELECT * FROM EMPLOYEES
WHERE GENDER = 'M'
AND LAST_NAME = 'Radwan';

-- Q4.
SELECT FIRST_NAME, LAST_NAME, EMP_NO
FROM EMPLOYEES
WHERE SUBSTR(EMP_NO, 1, 4) = 1030;

-- A4.
SELECT FIRST_NAME, LAST_NAME, EMP_NO
FROM EMPLOYEES
WHERE EMP_NO BETWEEN 10300 AND 10309;

-- Q5.
SELECT DISTINCT E.EMP_NO, E.FIRST_NAME, E.LAST_NAME, D.DEPT_NO
FROM EMPLOYEES E, DEPT_MANAGER D
WHERE E.EMP_NO = D.EMP_NO;

-- A5.
SELECT E.EMP_NO, E.FIRST_NAME, E.LAST_NAME, D.DEPT_NO
FROM EMPLOYEES E, DEPT_MANAGER D
WHERE E.EMP_NO = D.EMP_NO;

-- Q6.
SELECT COUNT(DISTINCT E.EMP_NO) AS CNT
FROM EMPLOYEES E, (
    SELECT EMP_NO
    FROM SALARIES
    WHERE SALARY > 50000
    ) S
WHERE E.EMP_NO = S.EMP_NO;

-- A6.
SELECT COUNT(E.EMP_NO) AS CNT
FROM EMPLOYEES E
WHERE EXISTS (
    SELECT 1
    FROM SALARIES S
    WHERE S.EMP_NO = E.EMP_NO
    AND S.SALARY > 50000);

SELECT * FROM table(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ALLSTATS LAST'));