CREATE TABLE CUSTOMER_GRADES (
    CUSTOMER_GRADE_ID NUMBER PRIMARY KEY,
    CUSTOMER_GRADE_NAME VARCHAR2(50) NULL
);

CREATE TABLE CUSTOMER_INFO (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NULL,
    SURNAME VARCHAR2(50) NULL,
    REGISTRATION_DATE DATE DEFAULT SYSDATE,
    CUSTOMER_GRADE_ID NUMBER NOT NULL,
    MARKETING_INFORMATION NUMBER(1) NULL,
    PERSONAL_INFORMATION NUMBER(1) NULL,
    CONSTRAINT "FK_GRADE_TO_CUSTOMER" FOREIGN KEY (CUSTOMER_GRADE_ID) REFERENCES CUSTOMER_GRADES (CUSTOMER_GRADE_ID)
);

CREATE TABLE ACCOUNT_INFO (
    ACCOUNT_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    ACCOUNT_NUMBER VARCHAR2(50) NULL,
    BALANCE NUMBER NULL,
    OPENING_DATE TIMESTAMP DEFAULT SYSDATE,
    ACCOUNT_STATUS NUMBER NULL,
    CLOSING_DATE TIMESTAMP NULL,
    CONSTRAINT "FK_CUSTOMER_TO_ACCOUNT" FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_INFO (CUSTOMER_ID)
);

CREATE TABLE STOCK_INFO (
    STOCK_ID NUMBER PRIMARY KEY,
    STOCK_NAME VARCHAR2(100) NULL,
    LISTING_DATE DATE NULL,
    EPS NUMBER NULL,
    BPS NUMBER NULL,
    PER NUMBER NULL,
    PBR NUMBER NULL,
    ROE NUMBER NULL,
    DIVIDEND_YIELD NUMBER NULL,
    CEO VARCHAR2(100) NULL,
    CREDIT_RATING NUMBER NULL
);

CREATE TABLE STOCK_PRICE_INFO (
    STOCK_ID NUMBER PRIMARY KEY,
    CURRENT_PRICE NUMBER NULL,
    PREVIOUS_CLOSING_PRICE NUMBER NULL,
    OPENING_PRICE NUMBER NULL,
    HIGH_PRICE NUMBER NULL,
    LOW_PRICE NUMBER NULL,
    TRADING_VOLUME NUMBER NULL,
    TRADING_VALUE NUMBER NULL,
    CONSTRAINT "FK_STOCK_INFO_TO_PRICE_INFO" FOREIGN KEY (STOCK_ID) REFERENCES STOCK_INFO (STOCK_ID)
);

CREATE TABLE STOCK_DIVIDENDS (
    STOCK_DIVIDEND_ID NUMBER PRIMARY KEY,
    DIVIDEND_DATE DATE NULL,
    DIVIDEND_AMOUNT NUMBER NULL,
    STOCK_ID NUMBER NOT NULL,
    ACCOUNT_ID NUMBER NOT NULL,
    CONSTRAINT "FK_STOCK_TO_DIVIDENDS" FOREIGN KEY (STOCK_ID) REFERENCES STOCK_INFO (STOCK_ID),
    CONSTRAINT "FK_ACCOUNT_TO_DIVIDENDS" FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT_INFO (ACCOUNT_ID)
);

CREATE TABLE SECURITIES_ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    ACCOUNT_ID NUMBER NOT NULL,
    STOCK_ID NUMBER NOT NULL,
    ORDER_AMOUNT NUMBER NULL,
    COMPLETED_AMOUNT NUMBER NULL,
    ORDER_DATE TIMESTAMP NULL,
    COMPLETED_DATE TIMESTAMP NULL,
    ORDER_TYPE NUMBER NULL,
    PRICE NUMBER NULL,
    CONSTRAINT "FK_ACCOUNT_TO_ORDERS" FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT_INFO (ACCOUNT_ID),
    CONSTRAINT "FK_STOCK_TO_ORDERS" FOREIGN KEY (STOCK_ID) REFERENCES STOCK_INFO (STOCK_ID)
);

CREATE TABLE TRANSACTION_FEES (
    TRANSACTION_FEE_ID NUMBER PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    FEE_AMOUNT NUMBER NULL,
    CONSTRAINT FK_ORDER_TO_FEES FOREIGN KEY (ORDER_ID) REFERENCES SECURITIES_ORDERS (ORDER_ID)
);

CREATE TABLE PROFIT_REPORTS (
    PROFIT_REPORT_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    START_DATE DATE NULL,
    END_DATE DATE NULL,
    START_AMOUNT NUMBER NULL,
    END_AMOUNT NUMBER NULL,
    CONSTRAINT "FK_CUSTOMER_TO_REPORTS" FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_INFO (CUSTOMER_ID)
);

CREATE TABLE SECURITIES_TRADES (
    TRADE_ID NUMBER PRIMARY KEY,
    BUY_ORDER_ID NUMBER NOT NULL,
    SELL_ORDER_ID NUMBER NOT NULL,
    TRADE_AMOUNT NUMBER NULL,
    TRADE_DATE TIMESTAMP NULL,
    TRADE_PRICE NUMBER NULL,
    CONSTRAINT "FK_BUY_ORDER_TO_TRADES" FOREIGN KEY (BUY_ORDER_ID) REFERENCES SECURITIES_ORDERS (ORDER_ID),
    CONSTRAINT "FK_SELL_ORDER_TO_TRADES" FOREIGN KEY (SELL_ORDER_ID) REFERENCES SECURITIES_ORDERS (ORDER_ID)
);

CREATE TABLE INVESTMENT_PORTFOLIO (
    INVESTMENT_PORTFOLIO_ID NUMBER PRIMARY KEY,
    STOCK_ID NUMBER NOT NULL,
    CUSTOMER_ID NUMBER NOT NULL,
    AMOUNT NUMBER NULL,
    AVERAGE_PRICE NUMBER NULL,
    CONSTRAINT "FK_STOCK_TO_PORTFOLIO" FOREIGN KEY (STOCK_ID) REFERENCES STOCK_INFO (STOCK_ID),
    CONSTRAINT "FK_CUSTOMER_TO_PORTFOLIO" FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_INFO (CUSTOMER_ID)
);

-- CUSTOMER_GRADES
INSERT INTO CUSTOMER_GRADES (CUSTOMER_GRADE_ID, CUSTOMER_GRADE_NAME) 
VALUES (1, 'Normal');

-- CUSTOMER_INFO
INSERT INTO CUSTOMER_INFO (CUSTOMER_ID, "NAME", SURNAME, REGISTRATION_DATE, CUSTOMER_GRADE_ID, MARKETING_INFORMATION, PERSONAL_INFORMATION) 
VALUES (1, 'John', 'Doe', SYSDATE, 1, 1, 1);

-- ACCOUNT_INFO
INSERT INTO ACCOUNT_INFO (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_NUMBER, BALANCE, OPENING_DATE, ACCOUNT_STATUS) 
VALUES (1, 1, '1111-111-111111', 1000, SYSDATE, 1);

-- STOCK_INFO
INSERT INTO STOCK_INFO (STOCK_ID, STOCK_NAME, LISTING_DATE, EPS, BPS, PER, PBR, ROE, DIVIDEND_YIELD, CEO, CREDIT_RATING) 
VALUES (1, 'MVIDIA', SYSDATE - 365, 5.23, 50.23, 10.0, 1.5, 15.2, 2.5, 'Jensen Wang', 5);

-- STOCK_PRICE_INFO
INSERT INTO STOCK_PRICE_INFO (STOCK_ID, CURRENT_PRICE, PREVIOUS_CLOSING_PRICE, OPENING_PRICE, HIGH_PRICE, LOW_PRICE, TRADING_VOLUME, TRADING_VALUE) 
VALUES (1, 102.5, 100.0, 101.0, 103.5, 100.5, 5000, 512500);

-- STOCK_DIVIDENDS
INSERT INTO STOCK_DIVIDENDS (STOCK_DIVIDEND_ID, DIVIDEND_DATE, DIVIDEND_AMOUNT, STOCK_ID, ACCOUNT_ID) 
VALUES (1, SYSDATE - 30, 2, 1, 1);

-- SECURITIES_ORDERS
INSERT INTO SECURITIES_ORDERS (ORDER_ID, ACCOUNT_ID, STOCK_ID, ORDER_AMOUNT, COMPLETED_AMOUNT, ORDER_DATE, COMPLETED_DATE, ORDER_TYPE, PRICE) 
VALUES (1, 1, 1, 100, 100, SYSDATE - 1, SYSDATE, 1, 102);

-- TRANSACTION_FEES
INSERT INTO TRANSACTION_FEES (TRANSACTION_FEE_ID, ORDER_ID, FEE_AMOUNT) 
VALUES (1, 1, 10);

-- PROFIT_REPORTS
INSERT INTO PROFIT_REPORTS (PROFIT_REPORT_ID, CUSTOMER_ID, START_DATE, END_DATE, START_AMOUNT, END_AMOUNT) 
VALUES (1, 1, SYSDATE - 30, SYSDATE, 1000, 1100);

-- SECURITIES_TRADES
INSERT INTO SECURITIES_TRADES (TRADE_ID, BUY_ORDER_ID, SELL_ORDER_ID, TRADE_AMOUNT, TRADE_DATE, TRADE_PRICE) 
VALUES (1, 1, 1, 100, SYSDATE, 102);

-- INVESTMENT_PORTFOLIO
INSERT INTO INVESTMENT_PORTFOLIO (INVESTMENT_PORTFOLIO_ID, STOCK_ID, CUSTOMER_ID, AMOUNT, AVERAGE_PRICE) 
VALUES (1, 1, 1, 100, 101);
