-- 거래 테이블에서 계좌별 누적 거래 금액을 계산하시오.
SELECT ACCOUNT_ID, TRANSACTION_DATE, AMOUNT, SUM(AMOUNT) OVER (
    PARTITION BY ACCOUNT_ID
    ORDER BY TRANSACTION_DATE
    ROWS BETWEEN UNBOUNDED PRECEDING
        AND CURRENT ROW
    ) CUM_AMOUNT
FROM TRANSACTIONS;

-- 거래 테이블과 계좌별 최고 거래 금액을 출력하시오.
SELECT T.*, MAX(AMOUNT) OVER (
    PARTITION BY ACCOUNT_ID
    ORDER BY ACCOUNT_ID
    ) MAX_AMOUNT
FROM TRANSACTIONS T;

-- 대출 테이블에서 지점별 누적 대출 금액을 계산하시오.
SELECT BRANCH_ID, LOAN_DATE, AMOUNT, SUM(AMOUNT) OVER (
    PARTITION BY BRANCH_ID
    ORDER BY LOAN_DATE
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) CUM_AMOUNT
FROM LOANS;

-- 계좌 테이블에서 고객별 평균 잔액을 계산하시오.
-- (반올림하여 소수점 둘째 자리까지 출력)
SELECT CUSTOMER_ID, BALANCE, 
    ROUND(
        AVG(BALANCE) OVER (
            PARTITION BY CUSTOMER_ID
            ORDER BY CUSTOMER_ID
        )
    ,2) AVG_BALANCE 
FROM ACCOUNTS;
