# -*- coding: utf-8 -*-
"""mymodule.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12JnhiAQiiMhnZ0daE02z4RakDrAIL_CY
"""

def add(a,b):
    return a+b

def subtract(a,b):
    return a-b