# -*- coding: utf-8 -*-
"""test_math.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12JnhiAQiiMhnZ0daE02z4RakDrAIL_CY
"""

import unittest
from mymodule import add, subtract # add, subtract 함수가 있는 모듈을 임포트

class TestMathFunctions(unittest.TestCase):

    def test_add(self):
        # 1 + 2가 3이어야 한다는 테스트
        self.assertEqual(add(1,2),3)

    def test_subtract(self):
        # 5 - 3가 2이어야 한다는 테스트
        self.assertEqual(subtract(5,3),2)

    def test_add_negative(self):
        # -1 + -2가 -3이어야 한다는 테스트
        self.assertEqual(add(-1,-2),-3)

    def test_subtract_negative(self):
        # -5 - (-3)가 -2이어야 한다는 테스트
        self.assertEqual(subtract(-5,-3),-2)

if __name__ == '__main__':
    unittest.main(argv=['first-arg-is-ignored'], exit=False)